@startuml Use Cases Hotel

actor Gast
actor Admin
actor HotelManager

rectangle hotel {
Gast --> (Hotel suchen)
Gast --> (Hotel ansehen)
Gast --> (Zimmer buchen)

Admin --> (Hotel anlegen)
Admin --> (Hotel ändern)
Admin --> (Hotel löschen)

HotelManager --> (Hotel suchen)
HotelManager --> (Hotel ändern)

    Admin --> (Zimmer verwalten)
    Admin --> (Standort pflegen)

}

footer (c) Halima Omer, Alisa Knöbl

@enduml